### ISSUE TITLE
Personalize automatic backup frequency

### ISSUE THREAD

**Issue by nicfab** [sergeymakinen/ResticScheduler#1]
Great project.
I see that the automatic backup frequency now involves only three options. 
Is it possible to customize the automatic frequency by setting other options?

**Comment by sergeymakinen** [comment]
Hey @nicfab, sure, just run `defaults write ru.makinen.ResticScheduler BackupFrequency -int 3600` (time in seconds) and relaunch the app (Backup Frequency would be displayed as Custom).

**Comment by nicfab** [comment]
> Hey @nicfab, sure, just run `defaults write ru.makinen.ResticScheduler BackupFrequency -int 3600` (time in seconds) and relaunch the app (Backup Frequency would be displayed as Custom).

Thank you very much.
However, I should set the frequency every time.
Do you plan to implement the opportunity to set up a personalized frequency without running the command line?

**Comment by sergeymakinen** [comment]
@nicfab Do you mean you want to change the frequency every time? If that's the cause, I could think on adding some UI to specify other intervals (not sure which UI should be used though). Because otherwise this setting is persistent after changing via the command line and will be remembered across launches.

**Comment by nicfab** [comment]
> @nicfab Do you mean you want to change the frequency every time? If that's the cause, I could think on adding some UI to specify other intervals (not sure which UI should be used though). Because otherwise this setting is persistent after changing via the command line and will be remembered across launches.

No, I mean to allow the user to choose the frequency without running the command.

**Comment by sergeymakinen** [comment]
I see. Ok, let's keep this open -- I'll add an UI to do this.
(I just hope this wouldn't evolve into a cron syntax too soon 😆)
